apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
spec:
  selector:
    name: mysql
    stage: dev
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306