apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ .Release.Name }}-ingress
spec:
  rules:
    - host: {{ .Release.Name }}.127.0.0.1.nip.io
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-service
              servicePort: 80
            path: /
