apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    name: application
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
spec:
  selector:
    name: mysql
    release: {{ .Release.Name }}
  ports:
    - port: 3306
      targetPort: 3306