apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-application-service
spec:
  selector:
    name: application
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      