apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
      stage: dev
  template:
    metadata:
      labels:
        app: nginx
        stage: dev
    spec:
      containers:
        - name: nginx
          image: nginx:{{ .Values.image.tag }}
          resources:
            limits:
              memory: "64Mi"
              cpu: "125m"
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: "/var/log/nginx"
            name: my-internal-pvc
      volumes:
        - name: my-internal-pvc
          persistentVolumeClaim:
            claimName: nginx-pvc