apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: wordpress
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: wordpress
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          resources:
            limits:
              memory: "512Mi"
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Release.Name }}-mysql
            - name: WORDPRESS_DB_USER
              value: user
            - name: WORDPRESS_DB_PASSWORD
              value: password
            - name: WORDPRESS_DB_NAME
              value: wordpress
          volumeMounts:
            - name: {{ .Release.Name }}-wordpress-claim
              mountPath: /var/www/html
      volumes:
        - name: {{ .Release.Name }}-wordpress-claim
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-wordpress-claim